name: Pull Request Changelog Check

on:
  pull_request:
    branches:
      - master

jobs:
  check_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Pull Request Changelog Check
        uses: mheap/pull-request-changelog-check@v1.2.0
        with:
          file: CHANGELOG
          error-message: 'The CHANGELOG file has not been updated in this pull request.'
